# ============================================================
# Framework Configuration
# Override any property via system property: -Dproperty=value
# ============================================================

# --------------- Platform ---------------
# Supported: android | ios
platform=android
# Supported: native | hybrid | web
app.type=native
app.installed=true

# --------------- Appium Server ---------------
appium.server.url=http://127.0.0.1
appium.server.port=4723

# --------------- Android ---------------
android.device.name=Pixel 9
android.app.package=com.todoproject.todoapp
android.app.activity=com.todoproject.todoapp.MainActivity
android.app.path=./src/test/resources/To-Do-App_1.5.apk
android.automation.name=UiAutomator2
android.no.reset=true

# --------------- iOS ---------------
ios.device.name=iPhone 16
ios.platform.version=17.0
ios.app.path=./src/test/resources/apps/app.app
ios.bundle.id=com.example.app
ios.automation.name=XCUITest
ios.no.reset=true
ios.wda.local.port=8100

# --------------- Browser ---------------
# Supported: Chrome | Safari
browser.name=Chrome
browser.url=https://www.google.com
chrome.driver.path=./src/test/resources/chromedriver.exe